services:
  - type: web
    name: todomanager
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn TodoManager.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TodoManager.settings
